[project]
name = "tutorx-mcp"
version = "0.1.0"
description = "Educational AI Tutor MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.3",
    "gradio>=4.19.0",
    "numpy>=1.24.0",
    "pillow>=10.0.0",
]
